import type { ImageMetadata } from "./types";

export type DemoImageSeed = {
  filename: string;
  url: string;
  width: number;
  height: number;
  fileSize: number;
  metadata: Omit<ImageMetadata, "id" | "image_id" | "created_at" | "updated_at">;
};

export const demoImages: DemoImageSeed[] = [
  {
    filename: "demo-sunlit-garden-flowers.jpg",
    url: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1200&q=80",
    width: 1200,
    height: 800,
    fileSize: 524000,
    metadata: {
      title: "Sunlit garden flowers in spring",
      description: "Close view of colorful garden flowers growing outdoors in soft natural daylight.",
      keywords: [
        "flowers",
        "garden",
        "spring",
        "nature",
        "outdoor",
        "sunlight",
        "bloom",
        "plant",
        "floral",
        "colorful",
        "green",
        "fresh",
        "growth",
        "botanical",
        "petals",
        "natural",
        "season",
        "landscape",
        "background",
        "copy space",
        "daylight",
        "environment",
        "park",
        "beauty",
        "close up",
        "summer",
        "peaceful",
        "organic",
        "decorative",
        "stock photo",
      ],
      category: "Nature",
      license_type_suggestion: "commercial",
      release_warning: null,
      quality_warning: null,
      ai_confidence_score: 0.91,
      user_edited: false,
    },
  },
  {
    filename: "demo-city-street-market.jpg",
    url: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=1200&q=80",
    width: 1200,
    height: 800,
    fileSize: 681000,
    metadata: {
      title: "Busy city street market scene",
      description: "People walking through an outdoor city market with shops and street activity.",
      keywords: [
        "city",
        "street",
        "market",
        "people",
        "urban",
        "travel",
        "walking",
        "shops",
        "public",
        "crowd",
        "tourism",
        "lifestyle",
        "outdoor",
        "architecture",
        "pedestrian",
        "destination",
        "local",
        "culture",
        "business",
        "commerce",
        "street scene",
        "town",
        "daylight",
        "event",
        "editorial",
        "community",
        "activity",
        "public place",
        "documentary",
        "stock photo",
      ],
      category: "Travel",
      license_type_suggestion: "editorial",
      release_warning: "Recognizable people and private storefronts may require releases for commercial use.",
      quality_warning: "Review for visible signs, logos, and faces before submitting.",
      ai_confidence_score: 0.86,
      user_edited: false,
    },
  },
  {
    filename: "demo-laptop-study-desk.jpg",
    url: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
    width: 1200,
    height: 800,
    fileSize: 612000,
    metadata: {
      title: "Laptop on clean study desk",
      description: "Simple workspace with a laptop on a desk, useful for education, study, and remote work themes.",
      keywords: [
        "laptop",
        "desk",
        "workspace",
        "study",
        "education",
        "student",
        "computer",
        "office",
        "remote work",
        "learning",
        "technology",
        "home office",
        "minimal",
        "table",
        "productivity",
        "online",
        "work",
        "school",
        "notebook",
        "clean",
        "modern",
        "business",
        "interior",
        "copy space",
        "typing",
        "internet",
        "freelance",
        "assignment",
        "course",
        "stock photo",
      ],
      category: "Technology",
      license_type_suggestion: "commercial",
      release_warning: "Check the laptop for visible logos before using commercially.",
      quality_warning: null,
      ai_confidence_score: 0.88,
      user_edited: false,
    },
  },
];
